# VantisVPN Clippy Configuration
# https://rust-lang.github.io/rust-clippy/

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Type complexity threshold
type-complexity-threshold = 250

# Allow certain lints
allow-expect-in-tests = true
allow-unwrap-in-tests = true

# Warn on specific things
too-many-arguments-threshold = 7